### ISSUE TITLE
Question about LGCAM

### ISSUE THREAD

**Issue by wuxchcandoit** [YangLiu9208/CMCIR#1]
Hi! Thanks for your great work!
Take the experiment on large-scale event-level urban dataset SUTD-TrafficQA as an example, I wonder which part of the code corresponds to LGCAM (Local-Global Causal Attention Module) in VLCIR_sutd_GAFN_bert.py?

**Comment by YangLiu9208** [comment]
Thanks for your interest in our work. The LGCAM model is in model/netvladv2.py. As shown in the following image: 
![image](https://github.com/YangLiu9208/CMCIR/assets/26245388/88f96216-aa3c-483f-b147-724f38679ea3)

**Comment by wuxchcandoit** [comment]
Oh! I see it! Thank you so much! But I encountered another problems. 
(a) It seems that there is only one branch corresponds to F_LG in the visual front-door causal intervention module instead of two branches (F_LG and F_LL). Why?
(b) q_proj and v_proj are calculated in the code while k_proj is not calculated.

**Comment by YangLiu9208** [comment]
I have checked the codes and find that you should use the " VLCIR_sutd_GAFN_bertv3.py". And I have uploaded this missing file in the model file. Thanks a lot!
![image](https://github.com/YangLiu9208/CMCIR/assets/26245388/e96bd9d2-6f7b-4252-b25d-543c2e580a2c)

Now, the LGCAM is calculated using the following codes for both appearance and motion features.
![image](https://github.com/YangLiu9208/CMCIR/assets/26245388/6d97053a-5eeb-4c3d-9eb9-fd22a3d797a1)

**Comment by wuxchcandoit** [comment]
Thank you for uploading the file VLCIR_sutd_GAFN_bertv3.py. But there are still some problems.
The class named GAFN_V3_self and the class named GAFN_V3_cluster are more like multi-model fusion module instead of LGCAM (Local-Global Causal Attention Module) because in class named GAFN_V3_cluster, the centroids which come from clusters serve as query (Q), which conflicts with the Fig 6 (the structure of Local-Global Causal Attention Module) in the paper.

**Comment by YangLiu9208** [comment]
The LGCAM is a causality-aware multi-model fusion module.
The fig6 of the paper shows the combination of GAFN_V3 and GAFN_V3_self.  We use GAFN_V3 and GAFN_V3_self in the paper, while the GAFN_V3_cluster is not considered in the paper because the GAFN_V3_cluster affect little to the overall performance.
