### ISSUE TITLE
执行预处理出错

### ISSUE THREAD

**Issue by DoubleSsh** [YangLiu9208/CMCIR#3]
作者您好
感谢您的工作
我遇到一个问题
我在使用代码预处理SUTD-TrafficQA时,使用python 1_preprocess_questions_oie.py --mode train,处理数据集下载的R3_train.jsonl,遇到:[('how many vehicles appeared', 0.8232), ('in this video', 0.2976), ('appeared in this', 0.2174)]
[('the road surface', 0.8108), ('of the road', 0.4241), ('what the condition of', 0.3788)]
[('would the accident still', 0.6809), ('move at lower', 0.3147), ('happen if the', 0.205)]
[('did car have collision', 0.9354), ('collision with other', 0.6761), ('with other cars', 0.5042)]
[('was there collision', 0.9854)]
Traceback (most recent call last):
  File "1_preprocess_questions_oie.py", line 43, in <module>
    sutd_qa.process_questions_oie_keybert_bert2(args)
  File "/media/lab/新加卷/linuxcode/CMCIR/Code/preprocess/datautils/sutd_qa.py", line 2508, in process_questions_oie_keybert_bert2
    token_relation =''.join(keywords[1][0])
IndexError: list index out of range
请问如何解决?如果能回复我,不胜感激

**Comment by lyoo122** [comment]
您好，我遇到了同样的问题，请问您有了什么解决办法吗？
若有打扰，非常抱歉，期待您的回复。

**Comment by ZhichaoWang6** [comment]
你好，请问你解决了吗
